version: '3.7'
services:
    postgres:
        container_name: postgres-${API_NAME}
        image: postgres:latest
        restart: always
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /data/postgres
        volumes:
            - ./docker/postgres/configs/postgres.conf:/etc/postgresql/postgresql.conf
            - ./docker/postgres/data:/var/lib/postgresql/data
            - ./docker/postgres/entrypoints/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '5'

    mongo:
        container_name: mongodb-${API_NAME}
        image: mongo:latest
        restart: always
        ports:
            - ${MONGODB_PORT}:27017
        env_file:
            - .env
        volumes:
            - ./docker/mongodb/entrypoints/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
            - ./docker/mongodb/data:/data/db
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '5'

    redis:
        container_name: redis-${API_NAME}
        image: redis:alpine
        restart: always
        ports:
            - ${REDIS_PORT}:6379
        command: redis-server --requirepass ${REDIS_PASSWORD}
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '5'

    api:
        container_name: api-${API_NAME}
        image: node:latest
        restart: always
        env_file:
            - .env
        depends_on:
            - postgres
            - mongo
            - redis
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        command: yarn start
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '5'
